### ISSUE TITLE
Dropdown navigation

### ISSUE THREAD

**Issue by mmcglynn** [mmcglynn/sfof#15]
The navigation needs to match [the designs](https://www.reignition.net/sfof-design/
![Screen Shot 2023-01-08 at 2 36 00 PM](https://user-images.githubusercontent.com/413484/211215443-6b99b6a0-ff15-4271-8a9b-f423a2a216d0.png)
![Screen Shot 2023-01-08 at 2 37 03 PM](https://user-images.githubusercontent.com/413484/211215444-15cb4c82-b08f-4c54-8837-8709830c6e0c.png)
).

**Comment by mmcglynn** [comment]
navigation styling is better but the other items look like they have empty drop downs.

https://www.reignition.net/temp/nav.mov

**Comment by jlopes1283** [comment]
This is using the wordpress Menu in Appearance > Menus.
<img width="559" alt="Screen Shot 2023-01-12 at 2 02 39 PM" src="https://user-images.githubusercontent.com/39833151/212157791-bc89acd2-9819-4775-a441-b3895df851e5.png">

New items need to be added from there in order for it to show.

**Comment by mmcglynn** [comment]
Still an issue. Has nothing to do with WP admin, it's a CSS issue. See the movie file.
