### ISSUE TITLE
Remove Featured Image capability for State posts

### ISSUE THREAD

**Issue by mmcglynn** [mmcglynn/sfof#25]
The state image on state pages is a design element. Because the client will be responsible for content updates, I don't want there to be a chance that they will overwrite the designed SVG files.

Please revert the feature so that posts for the 50 US states only pull the lest hand side image from the /assets folder.

**Comment by jlopes1283** [comment]
I made it so it will automatically pull the svg located in the '/assets/states/' folder. For this to work, the svg needs to be named exactly what the posts slug is. For example: Florida would be 'florida.svg' and Rhode Island would be 'rhode-island.svg'
