### ISSUE TITLE
Add missing section

### ISSUE THREAD

**Issue by mmcglynn** [mmcglynn/sfof#29]
Homepage is missing the card section. 

This is the design.
https://www.reignition.net/sfof-design/V4/desktop-home.jpg

This is the current page.
https://reignition-dev.com/

**Comment by jlopes1283** [comment]
The content is within the page in the backend but is being removed after the "[show-interactive-map]" shortcode on the the frontend. Think it's a script issue with the map

**Comment by mmcglynn** [comment]
All set.
