### ISSUE TITLE
Filtering no longer working

### ISSUE THREAD

**Issue by mmcglynn** [mmcglynn/sfof#39]
See attached. Filters don't work at all.

https://reignition-dev.com/tag/group/

![Screenshot 2023-02-27 at 19-47-59 Group – State Financial Officers Foundation](https://user-images.githubusercontent.com/413484/221723444-204919c7-2bc0-4d5a-af68-9b05ca287ff9.png)

**Comment by jlopes1283** [comment]
Fixed
